num_gpus: 1
exp_name: 'Debug'
N_vocab: 1500
max_steps: 1000000
root_dir: '/hub_data2/injae/nerf/nerf_synthetic/blender/lego'
feat_dir: '/hub_data2/injae/nerf/nerf_synthetic/blender/lego/dino_feature_map/'
pca_info_dir: '/hub_data2/injae/nerf/nerf_synthetic/blender/lego/dino_feature_map/'
out_dir: './logs'
dataset_name: 'blender'
object_type: 'lego'
blender:
  data_perturb: [] #['color', 'occ']
  img_wh: (400, 400)
train:
  batch_size: 1024   # num images for each batch
  num_work: 4
  randomized: True
  white_bkgd: False
  img_downscale: 2
val:
  batch_size: 1
  num_work: 4
  randomized: False
  white_bkgd: False
  check_interval: 0.15
  chunk_size: 4096  # The amount of input rays in a forward propagation
  img_idx: [0,1,2,3]  # validation images (indexing train images)
  log_image_list: ['rgb_fine','rgb_coarse','depth_fine','rgb_fine_static','_rgb_fine_transient','beta','alpha_fine_transient','feat_fine','_feat_fine_static','_feat_fine_transient', 'depth_coarse','rgb_coarse_static','_rgb_coarse_transient','beta','alpha_coarse_transient','feat_coarse','_feat_coarse_static','_feat_coarse_transient']
  img_downscale: 2
nerf:
  N_samples: 64  # The number of samples per level.
  N_importance: 64
  use_viewdirs: True  # If True, use view directions as a condition.
  use_disp: False
  perturb: 1.0
  noise_std: 0.
  disparity: False  # If True, sample linearly in disparity, not in depth.
  N_emb_xyz: 10
  N_emb_dir: 4
  encode_a: True
  a_dim: 48
  encode_t: True
  encode_t_front: False
  t_dim: 16
  beta_min: 0.1
optimizer:
  type: 'adam'
  lr: 5e-4
  scheduler:
    type: 'ExponentialLR'
    lr_end: 5e-5
optimizer_pose:
  type: 'adam'
  lr: 1e-3
  scheduler:
    type: 'ExponentialLR'
    lr_end: 1e-5
loss:
  coarse_loss: 0.5
checkpoint:
  resume_path: None
barf:
  refine: False
  camera:
    noise: 0.0
  c2f: #[0.1,0.5]
log:
  poses: True
  flag: 'default'